# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  config.vm.box = "jeqo/oracle-bpm-12c"

  config.vm.network :private_network, ip: "192.168.56.10"

  config.vm.network "forwarded_port", guest: 7001, host: 7001
  config.vm.network "forwarded_port", guest: 5004, host: 5004
  config.vm.network "forwarded_port", guest: 1521, host: 1521

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "3096"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbooks/oracle-bpm-12c-sample.yml"
  end
end
