---
  - template: src=templates/rcu-password-file.txt.j2 dest={{ rcu_password_file }}
    become: yes
    become_user: "{{ fmw_user }}"
  - name: Create Repository
    shell: "{{ mw_home }}/oracle_common/bin/rcu -silent -createRepository -databaseType ORACLE -connectString {{ db_hostname }}:{{ db_port }}:{{ db_oracle_sid }} -dbUser {{ db_dba_user }} -dbRole {{ db_dba_role }} -useSamePasswordForAllSchemaUsers true -schemaPrefix {{ db_schema_prefix }} -selectDependentsForComponents -component IAU -component OPSS -component SOAINFRA -f < {{ rcu_password_file }}"
    ignore_errors: yes
    become: yes
    become_user: "{{ fmw_user }}"
  - name: remove previous configuration
    file: path={{ rcu_password_file }} state=absent
