---
- name: Create BPM Suite 12c Domain (Compact)
  hosts: default
  remote_user: vagrant
  sudo: yes
  vars:
    fmw_user: oraclefmw
    domain_name: bpm_domain
    domains_home: /home/{{ fmw_user }}/config/domains
    apps_home: /home/{{ fmw_user }}/config/apps
    admin_username: weblogic
    admin_password: welcome1
    mw_home: /home/{{ fmw_user }}/product/Oracle_Home
    domain_script_file: /home/{{ fmw_user }}/domain.py
  tasks:
    - name: Generate Domain Creation WLST Script
      template: src=templates/domain.py.j2 dest={{ domain_script_file }}
      become: yes
      become_user: "{{ fmw_user }}"
    - name: Run WLST Script
      command: "{{ mw_home }}/oracle_common/common/bin/wlst.sh -skipWLSModuleScanning {{ domain_script_file }} > domain.log"
      become: yes
      become_user: "{{ fmw_user }}"
      args:
        chdir: /home/{{ fmw_user }}/
        creates: "{{ domains_home }}/{{ domain_name }}/config/config.xml"
    - name: Generate Start Server Upstart Script
      template: src=templates/wlsadminserver.conf.j2 dest=/etc/init/wlsadminserver.conf
    - name: Enable Service
      service: name=wlsadminserver enabled=yes
