---
  db_hostname: localhost
  db_port: 1521
  db_oracle_sid: XE
  db_dba_user: sys
  db_dba_password: welcome1
  db_dba_role: sysdba
  db_schema_prefix: DEV
  db_schema_password: welcome1
  rcu_password_file: "/tmp/rcu-password-file.txt"
